name: Build to Cloudflare Pages

permissions: write-all

on:
    pull_request:
        types: [opened, synchronize]

env:
    NODE_OPTIONS: '--max-old-space-size=8192'
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

jobs:
    build_to_cloudflare_pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v2

            - name: Get cached build output
              uses: actions/cache@v3
              with:
                key: ${{ runner.os }}-cache-public
                path: |
                    .cache
                    public
          
            - name: Get cached dependencies
              id: cache-npm
              uses: actions/cache@v3
              env:
                cache-name: cache-node-modules
              with:
                path: node_modules
                key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
  
            - name: Install dependencies
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Publish to Cloudflare Pages
              id: publish_to_pages
              run: |
                  echo "Installing Wrangler CLI"
                  npm i -g wrangler
                  
                  echo "Deploying build to Cloudflare Pages"
                  directory='public'
                  projectName='deriv-com-playground'
                  branch=$GITHUB_HEAD_REF
                  preview_url=$(wrangler pages deploy $directory --project-name=$projectName --branch=$branch | grep -o 'https://[^\"]*.pages.dev')
              
            - name: Retrieve Cloudflare Pages Preview URL
              id: vercel_preview_url
              uses: actions/github-script@v3
              with:
                  script: |
                      const preview_url = '${{ github.head_ref }}'
                      const comment = [
                        '| Name | Result |',
                        '| :--- | :------ |',
                        `| **Preview URL**  | [Visit Preview](${preview_url}) |`,
                        ''
                      ].join('\n')
                      core.setOutput("comment", comment);
                      
            - name: Post Cloudflare Pages Preview comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: Vercel Preview Comment
                  number: ${{github.event.issue.number}}
                  message: ${{steps.vercel_preview_url.outputs.comment}}

