name: Pre-generate preview link

on:
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: cloudflare-pages-verify-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    verify_pull_request:
        runs-on: Ubuntu-latest
        steps:
          - name: Save PR number
            run: |
              mkdir -p ./pr
              echo ${{ github.event.number }} > ./pr/NR
          - uses: actions/upload-artifact@v2
            with:
              name: "pr-${{github.run_id}}"
              path: pr/
