name: Pre-build to Cloudflare Pages

on:
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: cloudflare-pages-verify-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    verify_pull_request:
        runs-on: Ubuntu-latest
        steps:
            - name: Hewwo
              run: echo "hewwo"
